### ISSUE TITLE
Mouse LMB nor RMB work on Mac OS X

### ISSUE THREAD

**Issue by wyattbiker** [miskatonicstudio/goat#211]
I have 3.2. stable Mac OS X Mojave.

There is no hand cursor just a tiny dot cursor. I cannot get it to pickup/touch anything in the 2 minute room.

I checked all the settings (Esc) they look fine. WASD works. Mouse look works. Just Mouse buttons do nothing and no proper cursor.

**Comment by miskatonicstudio** [comment]
Thank you for reporting this. I do not have a MacOS machine, so it might take a moment to reproduce and fix this problem. Could you please provide some screenshots or, even better, a short movie that shows how the problem looks like on your computer? Your description was very clear, but it always help to see a picture ;)

**Comment by wyattbiker** [comment]
Ok after playing around it seems it is a user issue (ie me :). Just a question though.
When moving around the cursor in the game is the mouse cursor intended to be a tiny dot (when not pointing to any action item)? Where can I change the cursor to be a pointer arrow instead of that tiny dot? 

![image](https://user-images.githubusercontent.com/930478/73854884-39cb1880-4801-11ea-992a-789e1efd769f.png)

**Comment by miskatonicstudio** [comment]
Yes, the tiny dot is intentional. It is a "scope", that helps you in pointing at a specific object, as it is always at the center of the screen. When you approach an interactive object, the shape changes to indicate that an interaction is possible. I've seen a similar solution in other 3D adventure games, and decided that it would be good to have one in GOAT.

There is no setting for changing the dot into a mouse cursor, as having a mouse cursor as "scope" would probably look weird (mouse cursor indicates that you can move the mouse on the screen, while in fact you can only rotate the camera and point at different objects). If you want to use a mouse cursor shape nevertheless, you can edit the Player.tscn scene and replace the "Scope" label with a texture rect that shows a mouse cursor.

It would be a nice idea, though, to create a setting that would turn off the scope entirely, leaving only interaction icons. Some people might not want a scope in the middle of their screen. I will create a new task for that ;)

Let me know if you have other questions regarding this issue. If not, feel free to close the issue ;)

**Comment by wyattbiker** [comment]
Hey, thanks for the "scope" suggestion. That is what I was looking for. I changed it to an "X" instead of "." and works. I will close this issue.

**Comment by miskatonicstudio** [comment]
Hi @wyattbiker , a new setting was added to GOAT today, which allows you to hide or show the scope: #215 .I hope it will help you in your future experiments with this framework ;)
