### ISSUE TITLE
Add HTML detection for AO and reflection settings

### ISSUE THREAD

**Issue by miskatonicstudio** [miskatonicstudio/goat#228]
GotM export has some problems with these 2 settings.

**Comment by fritte2142** [comment]
Seems to be a browser issue and not a GotM issue as it issue is on Chrome but not Firefox.
OS can be detected in Godot with this: `OS.get_name() == "HTML5"`
The best solution is probably to detect if running in a browser and then disable AO and reflections so that the user has to manually enable them. Could also write our a note at those settings in the main menu, warning the user that not all browsers support them.

**Comment by miskatonicstudio** [comment]
This should be fixed now, along with DOF settings when the inventory is shown (that one was also causing problems). The solution to just disable some features is temporary, I hope, and as soon as Godot starts supporting those options I'll remove HTML detection :)
